### ISSUE TITLE
Operation behaviour seems weird

### ISSUE THREAD

**Issue by pwnorbitals** [nyx-space/hifitime#108]
Let's take as an example the following test from `duration.rs` : 

    assert_eq!(
        format!(
            "{}",
            TimeUnit::Hour * -5 + TimeUnit::Millisecond * -256 + TimeUnit::Nanosecond * -3
        ).trim(),
        "-5 h 0 min 0 s 256 ms 0 us 3 ns"
    );

This behaviour looks weird to me. In my opinion, addition of negative durations should behave like substraction of positive durations, here yielding `-6 h 59 min 59 s 743 ms 0 us 997 ns"

Am I wrong ?

**Comment by ChristopherRabotin** [comment]
Python3's `timedelta` works as you expect it to: if the duration is negative, everything but the largest field of a timedelta is positive:
```
>>> timedelta(hours=-5, milliseconds=-256, microseconds=-3e-3)
datetime.timedelta(days=-1, seconds=68399, microseconds=744000)
>>> timedelta(hours=-5, milliseconds=256, microseconds=3e-3)
datetime.timedelta(days=-1, seconds=68400, microseconds=256000)
>>> 
```

Note that I think this _only_ affects the printing and not the actual value of the duration since that's a two-float.

**Comment by pwnorbitals** [comment]
Fair enough that this would only be a printing issue. Not sure this is worth fixing in code, but we could update the docs to make it clear and avoid confusion when debugging `Duration`s

**Comment by ChristopherRabotin** [comment]
I think this is fixed with version 3, please check
