### ISSUE TITLE
v3.1 -- usability enhancement

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#118]
- [x] All Enums should be Copy, PartialEq, PartialOrd, Ord, Eq, Clone. TimeSystem (and likely other enums) are not copy. That's frustrating.
- [x] Epoch should derive Eq, Ord

**Comment by mkolopanis** [comment]
Should Epoch derive Ord? It looks like it only derives PartialOrd still even in v3.2.

**Comment by ChristopherRabotin** [comment]
Yes, it probably should. And it can be done trivially since it only uses
integers in the strict.
