### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by gwbres** [nyx-space/hifitime#178]
Hello @ChristopherRabotin,
we'd be interested in having a new release of this crate. 
Our rinex crate has been upgraded to make use of `Epoch` ([right here](https://github.com/gwbres/rinex/pull/45)) and we'd like to release it in a near future

**Comment by ChristopherRabotin** [comment]
Done! Version 3.7.0 is tagged and will be released as soon as the CI runs
through.


Christopher Rabotin.

**Comment by gwbres** [comment]
> Done! Version 3.7.0 is tagged and will be released as soon as the CI runs through

Thank you very much!
