### ISSUE TITLE
String format documentation incorrect

### ISSUE THREAD

**Issue by kiranshila** [nyx-space/hifitime#202]
The documentation says:
<html><body>

%H | Minute number, zero-padded to 2 digits | 39 for the 39th minutes of the hour | N/A
-- | -- | -- | --

</body>
</html>

but that is inconsistent with the C89 value. `%H` should be `hour as a decimal number, 24 hour clock (range [00-23])`. Additionally, the minute format, `%M` seems to be missing, which is what the `%H` description seems to be for.

**Comment by ChristopherRabotin** [comment]
I looked into it, and the documentation is wrong but the functionality is correctly implemented. I'll add a specific test to show that, but there should be not need for a code change.
