### ISSUE TITLE
Unit multiplication overflow

### ISSUE THREAD

**Issue by YizhePKU** [nyx-space/hifitime#205]
```
fn main() {
    let days = Unit::Day * (1_000_000);
    println!("{}", days); // prints 1196851200 days
}
```

**Comment by ChristopherRabotin** [comment]
Hi there,

This isn't an overflow issue. Typically an overflow issue is when the
result does not fit on the underlying representation and the result is
either a panic or garbage data.

In this case, you're hitting the maximum representation of a duration :
https://docs.rs/hifitime/latest/hifitime/struct.Duration.html#associatedconstant.MAX.
This corresponds to 31 centuries (with guaranteed nanosecond precision), or
about the typical lifespan of biological species.

I am considering implementing a large duration that would allow storing
much larger and much smaller durations. If that's a use case you have,
could you let me know in the relevant issue:
https://github.com/nyx-space/hifitime/issues/186.

Thanks
