### ISSUE TITLE
Epoch::from_format_str() does not set hours, minutes and seconds?

### ISSUE THREAD

**Issue by milgrim** [nyx-space/hifitime#248]
Hi!

I expected to see the hours, minutes and seconds to be set in this example:

````
use core::str::FromStr;
use hifitime::prelude::*;

fn main() {
    let test = Epoch::from_format_str("2023-117T12:55:26", "%Y-%jT%H:%M:%S").unwrap();
    println!("No hours, minutes, seconds?\n{}", test);
}
````
Output:

```
No hours, minutes, seconds?
2023-04-28T00:00:00 UTC
```

Am I doing something wrong?

**Comment by ChristopherRabotin** [comment]
That's definitely a bug, thanks for reporting it.

**Comment by ChristopherRabotin** [comment]
@milgrim Sorry for the delay in fixing this. The code fix is in, and will be published within the next hour (it's done automatically by Github as soon as I create the tag).

**Comment by milgrim** [comment]
No worries, thanks for the fix!

**Comment by ChristopherRabotin** [comment]
@milgrim just to let you know that in version 3.8.7, the behavior of this function has been fixed to match the behavior in Python: the day counter now starts at one instead of zero.

```
    >>> from datetime import datetime
    >>> dt, fmt = "2023-117T12:55:26", "%Y-%jT%H:%M:%S"
    >>> datetime.strptime(dt, fmt)
    datetime.datetime(2023, 4, 27, 12, 55, 26)
```
