### ISSUE TITLE
Best way to create a UTC Epoch with precise year

### ISSUE THREAD

**Issue by gwbres** [nyx-space/hifitime#256]
Hello Chris,

what is the best method to create a UTC Epoch with a specific amount of year.

Usually I use `from_utc_duration`, but we don't have a `Duration::from_years`.
We have `Duration::from_parts` with integer amount of centuries, but not fractionnal

```rust
let epoch = Epoch::from_utc_duration(Duration::from_days(3 * 365)); // error 1 year out of 4

let epoch = Epoch::from_utc_duration(
    Duration::compose(1, days, hours, ...)   // no year field
);
```

Other than using the string parser `Epoch::from_str("%04d"...")`

**Comment by ChristopherRabotin** [comment]
I usually use the FromStr trait and the ISO representation :
Epoch::from_str("2013-08-15 15:35:08 UTC")

More recently, I'm started using the Format submodule in hifitime that
allows specifying a format like RFC3339.

Does that answer your question or are you looking for an initialization
relative to the time system's reference epoch?

**Comment by gwbres** [comment]
Hello Chris,

> More recently, I'm started using the Format submodule in hifitime that allows specifying a format like RFC3339

Unfortunately the files I need to parse always have non standard ways to describe date times, they do not match RFC3339 for instance

> I usually use the FromStr trait and the ISO representation : Epoch::from_str("2013-08-15 15:35:08 UTC")

To answer my own question, one way to avoid an intermediate `Epoch::from_str` is to use `Epoch::from_gregorian_utc` which allows to pass all the Date Time parts.
