### ISSUE TITLE
from_gregorian but in GPST

### ISSUE THREAD

**Issue by gwbres** [nyx-space/hifitime#257]
Hello @ChristopherRabotin,

I would be interested in having an `Epoch` construction method similar  to `Epoch::from_gregorian_utc` but in `TimeScale::GPST`.

`from_gregorian_utc` is the best thing to use when all data fields are already known.

Such feature would solve the requirement I face in two of my parsers:

- in RINEX when parsing NAV ephemeris - the SV broadcasts Epoch expressed in their timescale (GPST for example)
- in SP3, all Epochs are expressed in a unique GNSS time scale

**Comment by ChristopherRabotin** [comment]
Yes, that's a good idea. Is this something we can implement in version 4?
It sounds like it would be quite a bit easier in there. What do you think?

**Comment by gwbres** [comment]
> It sounds like it would be quite a bit easier in there. What do you think?

Yes, definitely easier if the new approach gets finalized.

I don't have a need for this immediatly either

**Comment by ChristopherRabotin** [comment]
Would this make more sense in #229 to avoid proliferation of more initializers?

**Comment by gwbres** [comment]
I agree that if Epochs can be built from durations directly, it's okay to get rid of all the `from_xxx_seconds,nanoseconds` .
This will reduce code quantity and improve maintainability. (you did great in cleaning up the Epoch module BTW).

Now we have `Epoch::from_gregorian_str(x:x:x:x:x $TS)` which is very convenient to parse formatted epochs in specific timescales.
Ideally you want a mirror operation to go with that

**Comment by ChristopherRabotin** [comment]
Hi Guillaume,
This feature is already available it seems, and tested in the regression_test_gh_288 specifically with the GPST from str. I will add another test on the branch for 331 now.
