### ISSUE TITLE
Returns wrong Day of Year

### ISSUE THREAD

**Issue by gwbres** [nyx-space/hifitime#272]
Hello,

```rust
let epoch = Epoch::from_str("2021-12-21T00:00:00 GPST")
   .unwrap();

// weird result
println!("{:?}", epoch.years_days_of_year());
(1941, 29574.0)

// wrong result
println!("{:?}", epoch.day_of_year());
29574.0
```

**Comment by gwbres** [comment]
Confirmed there is a problem with all GNSS timescales

I have a partial workaround, it does not give correct results either, but "we'll do until a next release"

```rust
let doy = Epoch::from_duration_in_time_scale(gpst_epoch, TimeScale::UTC)
                  .day_of_year();
```

Noticed DOY is not tested for GNSS timescales in `tests/` .
This is probably where we should be headed

**Comment by ChristopherRabotin** [comment]
Hi Guillaume,

What is the expected result here? If I remember correctly, there's an ambiguity in calculating the year because of the reference year, but I forget where that ambiguity lies.

**Comment by gwbres** [comment]
> What is the expected result here? 

(2021, 355)

doy should be a value <= 365 as you would expect.
Currently we get (1941, 29k), where 29k = (2021 - 1941 )/ 365 + 355

**Comment by ChristopherRabotin** [comment]
I have a fix in progress, but there is an issue with GPST because the GPST ref epoch starts on 06 January and not 01 January. So should, for example "01 Jan 2022 GPST" return a day in year of zero (because zero full days have gone by) or should it return 360?

**Comment by gwbres** [comment]
> I have a fix in progress, but there is an issue with GPST because the GPST ref epoch starts on 06 January and not 01 January. So should, for example "01 Jan 2022 GPST" return a day in year of zero (because zero full days have gone by) or should it return 360?

Awesome Chris! 🎉 

It should return 0.xxx, the fractional day of year, as currently proposed, can be important in some applications (not mine though)

**Comment by gwbres** [comment]
I think it should return 0 because in DOY use cases, we usually imply the gregorian calendar.
What do you think ?

**Comment by ChristopherRabotin** [comment]
Yup, according to [NOAA](https://geodesy.noaa.gov/CORS/resources/gpscals.shtml), the counter starts at 1 and starts on 01 January.

**Comment by gwbres** [comment]
curious to read where the problem lies, once you submit it.

If we're certain about things, I'm interested in having a new release of your library, because 

- the new "%y formatter will facilate my parsers
- I am about to support RINEX standard naming conventions, and they use the DOY everywhere.
Most navigation data (interesting RINEX files) work in GNSS timescales (GPST, 99% of the time).
In this case, I workaround this very issue by converting to UTC, which slightly offsets the file name we're able to generate.

**Comment by ChristopherRabotin** [comment]
Let's make it happen!

**Comment by gwbres** [comment]
Thank you for all your support Chris.
Now I only have one more thing to do: correct my support of Clock RINEX and I'm off to PPP 😅
PPP will illustrate a lot more nyx

**Comment by ChristopherRabotin** [comment]
Sweet, looking forward to it!

**Comment by gwbres** [comment]
If you're fine with waiting until tomorrow, I will then add one or two similar tests to #273 for BDT/GST

**Comment by ChristopherRabotin** [comment]
Good idea.
