### ISSUE TITLE
Python submodule to support IDE type hints

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#304]
IDEs don't know what's in the Python module. This can be solved by writing `pyi` files. 

The goal of this task is to essentially repeat what Dora did here: https://github.com/dora-rs/dora/pull/493 .

**Comment by cardigan1008** [comment]
Hi @ChristopherRabotin , I'd like to give it a try. If it's convenient, please assign it to me.

**Comment by ChristopherRabotin** [comment]
With pleasure! I briefly tried the script from the `dora` repo linked above, but it didn't work out of the box, and I don't know why. Let me know if you can figure it out, otherwise, I can probably tackle it in early September according to my current backlog on the three Nyx Space repos.

**Comment by ChristopherRabotin** [comment]
@cardigan1008 , there's a new crate that aims to make this straight forward: https://github.com/PyO3/pyo3/issues/2454#issuecomment-2296314656 .  I have not tried it, but it looks quite promising!

**Comment by cardigan1008** [comment]
> @cardigan1008 , there's a new crate that aims to make this straight forward: [PyO3/pyo3#2454 (comment)](https://github.com/PyO3/pyo3/issues/2454#issuecomment-2296314656) . I have not tried it, but it looks quite promising!

Sounds great! Thanks for reminding. I’ll definitely give it a try soon.

**Comment by cardigan1008** [comment]
Hi @ChristopherRabotin 

Apologize for the delay in updating. I've just completed my project and have had the opportunity to try using pyo3-stub-gen. It turns out that some classes, such as LatestLeapSeconds, LeapSecondsFile, Ut1Provider, PyHifitimeError, PyDurationError, and PyParsingError, work well. However, there are some classes that don’t work as expected, primarily because pyo3-stub-gen fails to parse Duration into its own stub type.

The pyi file generated by pyo3-stub-gen can be found [here](https://gist.github.com/cardigan1008/461767929c0ceb8a87baefb3bba7ba29).

**Comment by ChristopherRabotin** [comment]
Hi there! No problem, this isn't a major rush. Good to know that it works in some cases but not others. Does the stub generator print an error when it fails by any chance? Thanks

**Comment by cardigan1008** [comment]
Yes, when I tried to implement it for Duration. The error goes like this:

```shell
error[E0433]: failed to resolve: could not find `any` in `std`
  --> src/duration/mod.rs:69:32
   |
69 | #[cfg_attr(feature = "python", gen_stub_pyclass)]
   |                                ^^^^^^^^^^^^^^^^
   |                                |
   |                                could not find `any` in `std`
   |                                in this procedural macro expansion
   |
  ::: /home/yunboni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-stub-gen-derive-0.6.0/src/lib.rs:22:1
   |
22 | pub fn gen_stub_pyclass(_attr: TokenStream, item: TokenStream) -> TokenStream {
   | ----------------------------------------------------------------------------- in this expansion of `#[gen_stub_pyclass]`
   |
help: consider importing this struct
   |
11 + use std::any::TypeId;
   |
```

**Comment by ChristopherRabotin** [comment]
Hi there,

Have you tried the recommended import that's shown in the compilation error?

Also, would it be possible for you to set up a PR with the changes the add the `gen_stub_pyclass? That way we can ensure that the type hints are built in the CI every time.

Thanks

**Comment by cardigan1008** [comment]
> Hi there,
> 
> Have you tried the recommended import that's shown in the compilation error?
> 
> Also, would it be possible for you to set up a PR with the changes the add the `gen_stub_pyclass? That way we can ensure that the type hints are built in the CI every time.
> 
> Thanks

I’ve tried the recommended import, but unfortunately, it still failed. It seems that the tool itself has some issues, and I’ve already proposed several issues regarding it. I’ll submit the PR to add the gen_stub_pyclass as soon as possible. However, please note that the PR may not cover all features.
