### ISSUE TITLE
Switch to Mozilla Public License

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#306]
After careful consideration, starting with version 4.0.0, Hifitime will be licensed in the Mozilla Public License (MPL) -- cf. the [Mozilla Public License FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) and [Github's _choose a license_](https://choosealicense.com/licenses/mpl-2.0/). This decision isn't taken lightly, nor is it final, and I want to ensure everyone in our community understands the rationale and practical implications. **This project exists for its users: please raise any concerns you have in this issue or on the discussion before version 4.0.0 is released.**

# Why the change?

The primary motivation behind this proposed shift is to better align with the core values of our project - promoting open-source collaboration while ensuring that improvements and derivatives remain open-source. MPL, I believe, will further foster a collaborative environment and ensure that enhancements remain accessible to all.

# Practical Implications for Users

1. Source Code Sharing: Under MPL, if you modify Hifitime's code, you are required to share those changes if you distribute the modified version. This requirement is more stringent than the Apache License, encouraging a more collaborative development environment.

2. Compatibility with Other Licenses: MPL is designed to be compatible with other open-source licenses (including BSD and Apache). For internal use within your organization, integrating Hifitime with other software poses no issues under the MPL. However, if distributing the modified version externally, ensure compatibility of MPL's requirements with licenses of external projects, particularly when dealing with restrictive licenses like the GNU General Public License (GPL) version 2.

3. Patent Rights: Like Apache, MPL grants patent rights from contributors to users. It's important to understand these rights, especially if you're using Hifitime in a commercial context.

4. No Warranty: As with most open-source software, Hifitime under MPL would be provided without warranty. This aspect remains unchanged from the Apache License.

# Your Feedback Matters

This proposal is not final, and your feedback is crucial. I invite all users and contributors to share their thoughts, concerns, or support for this change. Understanding how this impacts your use and contribution to Hifitime will guide me in making a decision that best serves our community.

Please share your thoughts in this discussion thread or reach out directly if you prefer a more private conversation.

Thank you for your continued support and contributions to Hifitime. Together, we're not just building software; we're fostering a community that drives innovation for spaceflight dynamics.

_Originally posted by @ChristopherRabotin in https://github.com/nyx-space/hifitime/discussions/274_

**Comment by gwbres** [comment]
I don't know if that is still the case (I'm far from interested by these topics), but the "standards for Rust libraries" is MIT+Apache 2. 
I personnally don't like MIT which is too broad, I particularly like this idea:

> 1. Source Code Sharing: Under MPL, if you modify Hifitime's code, you are required to share those changes if you distribute the > modified version. This requirement is more stringent than the Apache License, encouraging a more collaborative development 
> environment.

We spend so much time developping all of this (mostly for fun, as far as i'm concerned), that it gets hard to understand if people get to use the software or potentially improve it without contributing back to the projectS
