### ISSUE TITLE
from_gregorian_hms and to_gregorian_str dose not work as expected

### ISSUE THREAD

**Issue by cokkiy** [nyx-space/hifitime#327]
Here is the sample test code:
```
#[test]
    fn test_epoch_time() {
        let epoch = Epoch::from_gregorian_hms(2020, 1, 1, 0, 0, 0, TimeScale::GPST);

        assert_eq!(
            epoch.to_gregorian_str(TimeScale::UTC),
            "2019-12-31T23:59:23 UTC"
        );

        assert_eq!(
            epoch.to_gregorian_str(TimeScale::GPST),
            "2020-1-1T0:0:0 GPST"
        );
    }
```
The second assert doesn't pass as expected, the result is "2019-12-31T23:59:23 GPST"  but I hope it should be "2020-01-01T00:00:00 GPST". Is I misunderstanding those API or is there a bug?

**Comment by ChristopherRabotin** [comment]
Hi Cokkiy,

Are you using hifitime version 3.x? We're almost ready to release version 4.0.0 and that version has indeed fixed a bug with that function: https://github.com/nyx-space/hifitime/pull/308/files .

The following test passes with version 4.0.0-alpha.

```rust
#[test]
fn test_gh_327() {
    let epoch = Epoch::from_gregorian_hms(2020, 1, 1, 0, 0, 0, TimeScale::GPST);

    assert_eq!(
        epoch.to_gregorian_str(TimeScale::GPST),
        "2020-01-01T00:00:00 GPST"
    );
}
```

I encourage you to switch to hifitime version 4.0.0-alpha. There will be a handful of breaking changes between 4.0.0-alpha and the stable version of hifitime, but version 4 fixes a lot of small bugs like these.

Let me know if you have any other questions, and if not, feel free to close this issue.
