### ISSUE TITLE
Convert crate to no-std

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#64]
This will help us use it more easily on an embedded board without worry.

Quote from Matrix.org:
> **jplatte**
> xionbox: A good way to start is simply adding #![no_std] to your lib.rs and trying to convert all usages of std to the same things from core. You'll quickly notice whether there's stuff only in std that you depend on directly
> Then you have to check all your dependencies to see whether they're all no_std or can be configured as such (often this is simply default-features = false)
> There's little more to know beyond that AFAIK
> https://github.com/core-error/core-error might be interesting if your library has its own error type(s)

Another potentially useful resource: https://github.com/johnthagen/min-sized-rust

**Comment by ChristopherRabotin** [comment]
This is actually hard because `f64` is missing useful features, notably `sin`, `div_euclid`, and `rem_euclid`. The `micromath` crate could be used, but it currently only supports 32-bit floats (and this library aims to be very precise, so 64 bit floats are required).

**Comment by joseluis** [comment]
[libm](https://crates.io/crates/libm) could be another alternative since it supports f64 no_std math operations.

**Comment by ChristopherRabotin** [comment]
This works great, thanks!

For reference, I tested out the following for the sin/asin (hifitime uses it for the TDB computation).

```
#![no_std]

extern crate libm;

#[test]
fn test_main() {
    let bound = core::f64::consts::FRAC_PI_2;
    let step = core::f64::consts::FRAC_PI_2 / 18.0;
    let mut alpha = -bound + 10.0 * step;

    while alpha < bound {
        let sined = alpha.sin();
        let asined = sined.asin();
        assert!(
            (asined - alpha).abs() < 5.0 * core::f64::EPSILON,
            "asin(sin({alpha})) = {asined} !"
        );

        alpha += step;
    }
}
```
