### ISSUE TITLE
Optionally allow Chronos conversions for timezone handling

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#73]
This is helpful to support human-time which isn't UTC.

**Comment by ChristopherRabotin** [comment]
This is getting useful when converting data from sources which do not use ISO.

**Comment by mpfaff** [comment]
If you're considering optional chrono support, can you do the same for time?

**Comment by ChristopherRabotin** [comment]
Yes, probably. I'm just not totally sure what chrono brings to the table at
the moment. What features of chrono would you consider essential to a date
and time management library?

**Comment by mpfaff** [comment]
My primary use for time (I prefer time over chrono) is formatting and parsing.

**Comment by ChristopherRabotin** [comment]
OK. Is support for the RFC 3339 something you're looking for? I just went
through the documentation of chrono and I can't tell what it does that
hifitime can't apart from an initializer using system time. Maybe I'm
missing something?

**Comment by mpfaff** [comment]
I don't currently have a use for hifitime where time/chrono wouldn't suffice. With that being said, if I were to use hifitime I would want to be able to parse and format RFC-3339 and get the current time from whatever system clock is available.

**Comment by ChristopherRabotin** [comment]
Work plan:
- [ ] Include offsets in RFC3339 format (these can be easily converted to a Duration)
- [ ] If the time system is not recognized (e.g. `BST`), and the `timezones` feature is enabled, then the `FromStr` implementation should call `chrono-tz` to parse the timezone by identifier.
- [ ] If `timezones` feature is enabled, then the chrono datetime type should be castable into an Epoch.

**Comment by ChristopherRabotin** [comment]
Chrono-tz does not support converting a named timezone into an offset, only the other way around. Therefore, this issue cannot be completed as such.

Instead, this feature had focused on correctly parsing RFC3339.

**Comment by ChristopherRabotin** [comment]
Parsing RFC3339 (zulu and with offset) and getting the system time is now available via #149 .
